### PR TITLE
Adaptive complexes page

### PR DESCRIPTION
**Pull request by barbagrigia**

### CODE REVIEW

**Comment by barbagrigia** [comment]
https://yard-frontend-zvpalewxzr.now.sh

**Comment by imevro** [comment]
По бокам 64? Надо же 16

image

**Comment by barbagrigia** [comment]
https://yard-frontend-axnlejcvfe.now.sh

**Comment by barbagrigia** [comment]
https://yard-frontend-rsytxlbhah.now.sh

**Comment by barbagrigia** [comment]
https://yard-frontend-apdnfyddzn.now.sh
с jq-шным api

**Pull request merged**
